/**
 * DealFlow360 Customer Portal Mock Data Store
 * Matches exact UI screenshots for Acme Corporation
 */

export const INITIAL_USER = {
  name: "Rohan Kapoor",
  role: "Procurement Director",
  email: "rohan.kapoor@acme-corp.com",
  phone: "+91 98200 45678",
  initials: "RK",
  customerOrg: {
    id: "cust_acme_2026",
    name: "Acme Corporation",
    shortCode: "AC",
    gstin: "27AAACA1234A1Z5",
    pan: "AAACA1234A",
    addressLine1: "Tech Park IV, 5th Floor, Tower B",
    addressLine2: "Outer Ring Road, Kadubeesanahalli",
    city: "Bengaluru",
    state: "Karnataka",
    postalCode: "560103",
    country: "India",
  },
};

export const INITIAL_METRICS = {
  activeQuotations: 2,
  activeQuotationsNote: "1 needs your attention",
  underNegotiation: 1,
  underNegotiationNote: "Updated 12 min ago",
  awaitingApproval: 1,
  awaitingApprovalNote: "Sales team reviewing",
  confirmedOrders: 3,
  confirmedOrdersTotalValue: "₹24,80,000 total value",
};

export const INITIAL_QUOTATIONS = [
  {
    id: "Q-2026-0042",
    date: "05 Sep 2026",
    validUntil: "15 Sep 2026",
    salesRep: "Aarav Mehta",
    salesRepRole: "Account executive",
    lineItemsCount: 3,
    subtotal: 1497500,
    discountAmount: 147500,
    taxAmount: 90000,
    total: 1340000,
    status: "Under Negotiation",
    lastUpdated: "12 min ago",
    items: [
      {
        id: "item-1",
        name: "Laptop Pro 16\"",
        description: "Enterprise configuration · 32GB RAM · 1TB SSD · Apple M3 Max",
        quantity: 10,
        unitPrice: 150000,
        discountPercent: 12,
        total: 1320000,
      },
      {
        id: "item-2",
        name: "Setup & onboarding",
        description: "On-site installation and team onboarding package with 24/7 priority SLA",
        quantity: 1,
        unitPrice: 50000,
        discountPercent: 5,
        total: 47500,
      },
      {
        id: "item-3",
        name: "Enterprise Security Key YubiKey 5C",
        description: "FIPS 140-2 certified hardware security key",
        quantity: 10,
        unitPrice: 4500,
        discountPercent: 10,
        total: 40500,
      },
    ],
    conversation: [
      {
        id: "msg-1",
        sender: "Aarav Mehta",
        senderRole: "Sales Representative",
        avatarText: "AM",
        isCustomer: false,
        time: "10:04 AM",
        message: "Can we help with anything on this quotation?",
      },
      {
        id: "msg-2",
        sender: "You",
        senderRole: "Acme Corporation",
        avatarText: "RK",
        isCustomer: true,
        time: "10:16 AM",
        message: "Could you do 15% if we increase the quantity?",
      },
      {
        id: "msg-3",
        sender: "Aarav Mehta",
        senderRole: "Sales Representative",
        avatarText: "AM",
        isCustomer: false,
        time: "10:21 AM",
        message: "I can offer 13% today. I have sent your 15% request for approval.",
      },
    ],
  },
  {
    id: "Q-2026-0038",
    date: "28 Aug 2026",
    validUntil: "10 Sep 2026",
    salesRep: "Aarav Mehta",
    salesRepRole: "Account executive",
    lineItemsCount: 5,
    subtotal: 950000,
    discountAmount: 75000,
    taxAmount: 80000,
    total: 875000,
    status: "Sent",
    lastUpdated: "28 Aug 2026",
    items: [
      {
        id: "item-201",
        name: "Cloud Workstations Pro",
        description: "Virtual cloud dev boxes with dedicated GPU",
        quantity: 5,
        unitPrice: 175000,
        discountPercent: 8,
        total: 805000,
      },
      {
        id: "item-202",
        name: "24/7 Managed NOC Support",
        description: "Annual monitoring contract",
        quantity: 1,
        unitPrice: 70000,
        discountPercent: 0,
        total: 70000,
      },
    ],
    conversation: [
      {
        id: "msg-201",
        sender: "Aarav Mehta",
        senderRole: "Sales Representative",
        avatarText: "AM",
        isCustomer: false,
        time: "Aug 28, 02:30 PM",
        message: "Hi Rohan, shared the updated pricing for the cloud workstations.",
      },
    ],
  },
  {
    id: "Q-2026-0029",
    date: "12 Aug 2026",
    validUntil: "25 Aug 2026",
    salesRep: "Nisha Shah",
    salesRepRole: "Account executive",
    lineItemsCount: 2,
    subtotal: 450000,
    discountAmount: 30000,
    taxAmount: 35000,
    total: 420000,
    status: "Confirmed",
    lastUpdated: "18 Aug 2026",
    items: [
      {
        id: "item-301",
        name: "Network Switches 48-Port PoE+",
        description: "Gigabit Managed Layer 3 switch",
        quantity: 2,
        unitPrice: 210000,
        discountPercent: 7,
        total: 390600,
      },
    ],
    conversation: [
      {
        id: "msg-301",
        sender: "Nisha Shah",
        senderRole: "Sales Representative",
        avatarText: "NS",
        isCustomer: false,
        time: "Aug 18, 11:15 AM",
        message: "Quotation approved and order SO-2026-00881 confirmed! Thank you.",
      },
    ],
  },
];

export const INITIAL_ORDERS = [
  {
    id: "SO-2026-00881",
    quotationId: "Q-2026-0029",
    date: "18 Aug 2026",
    itemsCount: 10,
    total: 420000,
    status: "Confirmed",
    deliveryEstimate: "22 Sep 2026",
    fulfillmentStage: "Warehouse Dispatch",
  },
  {
    id: "SO-2026-00764",
    quotationId: "Q-2026-0018",
    date: "03 Aug 2026",
    itemsCount: 5,
    total: 2060000,
    status: "Confirmed",
    deliveryEstimate: "Delivered",
    fulfillmentStage: "Delivered & Signed",
  },
];

export const INITIAL_BILLING = {
  outstandingBalance: "₹5,000",
  outstandingDueDate: "Due 05 Oct 2026",
  paidThisYear: "₹24,80,000",
  paidInvoicesCount: "Across 4 invoices",
  nextRecurringCharge: "₹5,000",
  nextRecurringDate: "05 Oct 2026",
  invoices: [
    {
      id: "INV-2026-1042",
      orderId: "SO-2026-00881",
      date: "05 Sep 2026",
      amount: 5000,
      dueDate: "05 Oct 2026",
      status: "Pending Approval",
    },
    {
      id: "INV-2026-0981",
      orderId: "SO-2026-00864",
      date: "05 Aug 2026",
      amount: 840000,
      dueDate: "Paid",
      status: "Confirmed",
    },
    {
      id: "INV-2026-0870",
      orderId: "SO-2026-00847",
      date: "05 Aug 2026",
      amount: 840000,
      dueDate: "Paid",
      status: "Confirmed",
    },
  ],
};

export const INITIAL_ACTIVITIES = [
  {
    id: "act-1",
    title: "Quotation updated",
    description: "Q-2026-0042 · Aarav Mehta",
    time: "17 min ago",
    type: "update",
  },
  {
    id: "act-2",
    title: "Counter offer submitted",
    description: "15% discount request",
    time: "24 min ago",
    type: "counter_offer",
  },
  {
    id: "act-3",
    title: "Discount approved",
    description: "Q-2026-0029 · 10% approved",
    time: "18 Aug 2026",
    type: "approval",
  },
];
